spring:
  application:
    name: cat-api
  main:
    banner-mode: off
  jmx:
    enabled: false
  flyway:
    baselineOnMigrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          randomCoffee:
            url: http://cat-recommender-api:8080
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

app:
  number-of-cats-to-add-on-startup: 20000
  batch-size: 20000

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

springdoc:
  cache:
    disabled: true
  swagger-ui:
    url: /openapi.yaml
