receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp:
    protocols:
      grpc:
      http:

#  Not supported in v0.80
#  postgresql:
#    endpoint: cat-api-postgres:5432
#    transport: tcp
#    username: postgres
#    password: postgres
#    databases:
#      - cats
#    metrics:
#      postgresql.sequential_scans:
#        enabled: true
#    collection_interval: 10s
#    tls:
#      insecure: true
#      insecure_skip_verify: true

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
    add_metric_suffixes: false # Otherwise, SPM doesn't work with otel_collector 0.88 (works with 0.80).

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

connectors:
  spanmetrics:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch] #transform
      exporters: [spanmetrics, otlp]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
#    not supported in 0.80
#    metrics/postgresql:
#      receivers: [postgresql]
#      processors: [batch]
#      exporters: [prometheus]

