name: Publish Python Docker image
on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    branches: [main]
    types:
      - completed
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./cat-recommender
          username: ${{ github.actor }}
          password: ${{ github.token }}
          push: true
          image: ghcr.io/egorklimov/test-assignment/cat-recommender
          tags: 0.0.1